### PR TITLE
Prepare models

### PR DESCRIPTION
**Pull request by AlbertPG**

### CODE REVIEW

**Review by enrichp — APPROVED** [review]

**Review by santidrj — APPROVED** [review]
:+1:

**Comment by AlbertPG** [comment]
[Prepare models](https://trello.com/c/gigQgEyO/38-prepare-models)

**Comment by AlbertPG** [comment]
[Add CORS to API implementation](https://trello.com/c/vSceE7Fe/43-add-cors-to-api-implementation)

**Comment by AlbertPG** [comment]
[API for contributions](https://trello.com/c/GPWln3IV/41-api-for-contributions)

**Pull request merged**
