### PR TITLE
Threads reply

### PR DESCRIPTION
**Pull request by enrichp**

### CODE REVIEW

**Comment by enrichp** [comment]
[Comments list](https://trello.com/c/S7M4mVJJ/25-comments-list)

**Comment by enrichp** [comment]
Karma implementation and correct the problems with the last merges.

**Comment by enrichp** [comment]
[Thread list](https://trello.com/c/0ElWSCzC/23-thread-list)

**Review by xavier-campos-diaz — APPROVED** [review]

**Review by AlbertPG — APPROVED** [review]
I see no problems at all

**Pull request merged**
