### PR TITLE
Threads and comments

### PR DESCRIPTION
**Pull request by enrichp**

### CODE REVIEW

**Review by AlbertPG — APPROVED** [review]
I see no problem

**Review by santidrj — APPROVED** [review]
👍

**Comment by enrichp** [comment]
[Comments list](https://trello.com/c/S7M4mVJJ/25-comments-list)

**Comment by enrichp** [comment]
[Thread list](https://trello.com/c/0ElWSCzC/23-thread-list)

**Review by marclll — APPROVED** [review]
Weeeeell Done Boys

**Pull request merged**
