### PR TITLE
Main page login

### PR DESCRIPTION
**Pull request by marclll**

### CODE REVIEW

**Review by enrichp — APPROVED** [review]

**Review by AlbertPG — APPROVED** [review]
Okey

**Review by xavier-campos-diaz — APPROVED** [review]

**Review by AlbertPG — APPROVED** [review]
Okey

**Review by santidrj — APPROVED** [review]
👍

**Comment by marclll** [comment]
[Home Page New interface](https://trello.com/c/rJWy4WeZ/4-home-page-new-interface)

**Comment by marclll** [comment]
[Main Page not logged interface](https://trello.com/c/yOzbrUqW/7-main-page-not-logged-interface)

**Comment by marclll** [comment]
[Main page logged interface](https://trello.com/c/RleGddbY/2-main-page-logged-interface)

**Pull request merged**
