### PR TITLE
Login

### PR DESCRIPTION
**Pull request by enrichp**

### CODE REVIEW

**Review by AlbertPG — APPROVED** [review]
Everything seems correct

**Review by santidrj — APPROVED** [review]
👍

**Comment by enrichp** [comment]
[Login and logout to the application with Google](https://trello.com/c/C1hxfnpL/18-login-and-logout-to-the-application-with-google)

**Comment by enrichp** [comment]
[Edit user profile](https://trello.com/c/FtSAN6GW/20-edit-user-profile)

**Pull request merged**
