### PR TITLE
Submit page

### PR DESCRIPTION
**Pull request by AlbertPG**

### CODE REVIEW

**Comment by AlbertPG** [comment]
[Interface implementation](https://trello.com/c/p4mTRDFO/3-interface-implementation)

**Comment by AlbertPG** [comment]
[URL contributions](https://trello.com/c/jwbUkfkj/5-url-contributions)

**Comment by AlbertPG** [comment]
[URL contributions](https://trello.com/c/jwbUkfkj/5-url-contributions)

**Review by xavier-campos-diaz — APPROVED** [review]

**Comment by AlbertPG** [comment]
[Ask contributions](https://trello.com/c/3rWmYJGZ/6-ask-contributions)

**Review by marclll — APPROVED** [review]
Mmmmmm

**Review by enrichp — APPROVED** [review]

**Pull request merged**
