### PR TITLE
Main page

### PR DESCRIPTION
**Pull request by marclll**

### CODE REVIEW

**Review by xavier-campos-diaz — APPROVED** [review]

**Review by enrichp — APPROVED** [review]

**Review by AlbertPG — APPROVED** [review]
Okey

**Review by santidrj — APPROVED** [review]
👍

**Comment by marclll** [comment]
[Main page: See more pages](https://trello.com/c/f4YbzZ8X/28-main-page-see-more-pages)

**Comment by marclll** [comment]
[Home Page New interface](https://trello.com/c/rJWy4WeZ/4-home-page-new-interface)

**Comment by marclll** [comment]
[Main Page not logged interface](https://trello.com/c/yOzbrUqW/7-main-page-not-logged-interface)

**Comment by marclll** [comment]
[Main page logged interface](https://trello.com/c/RleGddbY/2-main-page-logged-interface)

**Comment by marclll** [comment]
[Upvote contributions](https://trello.com/c/ID653dNb/14-upvote-contributions)

**Comment by marclll** [comment]
[Hide Contributions](https://trello.com/c/zC7u23oX/15-hide-contributions)

**Comment by marclll** [comment]
[See contributions ordered](https://trello.com/c/IHBvPn5Y/9-see-contributions-ordered)

**Pull request merged**
