### PR TITLE
Reply

### PR DESCRIPTION
**Pull request by AlbertPG**

### CODE REVIEW

**Review by enrichp — APPROVED** [review]

**Comment by AlbertPG** [comment]
[Reply to a comment](https://trello.com/c/eZDqcjVw/13-reply-to-a-comment)

**Comment by AlbertPG** [comment]
[Vote comment](https://trello.com/c/S9KLnm7M/16-vote-comment)

**Comment by AlbertPG** [comment]
[Vote reply](https://trello.com/c/ABlK2Tln/17-vote-reply)

**Review by xavier-campos-diaz — APPROVED** [review]

**Comment by AlbertPG** [comment]
[Vote comment](https://trello.com/c/S9KLnm7M/16-vote-comment)

**Pull request merged**
